### ISSUE TITLE
I successfully installed natten0.17.3+torch2.5.0 using MSVC, but I have multiple ComfyUI, could you tell me how to build a whl file

### ISSUE THREAD

**Issue by lldacing** [2kpr/ComfyUI-PMRF#13]
I successfully installed natten0.17.3+torch2.5.0 using MSVC, just get a egg file, but I have multiple ComfyUI, could you tell me how to build a whl file. 
Thx

**Comment by lldacing** [comment]
I got it

**Comment by chensyo** [comment]
Could you please tell me how to do it?
